---
title: TuHoc.ML
timezone: Asia/Ho_Chi_Minh
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    social-share: true
- scope:
    path: ''
  values:
    layout: page
    show-avatar: true
url: https://tuhoc.ml
baseurl: ''
description: Thế giới Machine Learning của những người vui tính
navbar-links:
  Tra cứu:
  - Danh mục: categories
  - Tags: tags
  - Chính sách: policy
  Về nhóm tác giả: aboutme
  <i class="fa fa-search" aria-hidden="true"></i>: search
title-img: "/img/avatar-new.png"
navbar-col: "#353535"
navbar-text-col: "#dedede"
navbar-children-col: "#353535"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"
author:
  name: Mandevices AI team
social-network-links:
  rss: true
  email: levulinhbk@gmail.com
  facebook: levulinhbk
  github: levulinh
share-links-active:
  twitter: true
  facebook: true
  google: true
  linkedin: true
url-pretty: tuhoc.ml
fb_comment_id: '462955144219041'
fb_app_id: '462955144219041'
excerpt_length: 50
title-separator: "-"
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 5
kramdown:
  input: GFM
link-tags: true
exclude:
- CHANGELOG.md
- CNAME
- Dockerfile
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- Vagrantfile
prose:
  rooturl: _posts
  media: meida
  ignore:
  - 404.html
  - LICENSE
  - feed.xml
  - "/css"
  - "/img"
  - "/js"
  metadata:
    _posts:
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: Post title
        placeholder: Title
        alterable: true
    - name: subtitle
      field:
        element: textarea
        label: Subtitle
        placeholder: A description of your post.
        alterable: true
    - name: date
      field:
        element: text
        label: Date
        help: Enter date of post.
        placeholder: yyyy-mm-dd
        alterable: true
    - name: bigimg
      field:
        element: text
        label: Image
        help: Add a cover image to your post.
        placeholder: Thumbnail
        alterable: true
    - name: author
      field:
        element: select
        label: Post author
        options:
        - name: Lê Vũ Linh
          value: levulinh
    - name: published
      field:
        element: checkbox
        label: Publish
        help: Check to publish post, uncheck to hide.
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
